disabled_rules:
- line_length
- trailing_whitespace
- orphaned_doc_comment
- nesting
- function_body_length
- function_parameter_count
- force_try

opt_in_rules:
- anyobject_protocol
- let_var_whitespace
- force_cast


excluded:
- SeSAC-Memo/Application

identifier_name:
  excluded:
    - id
    - URL

force_cast:
    warning
